# Generated by Django 4.1.3 on 2023-02-17 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=852)),
                ('grv_number', models.CharField(max_length=255)),
                ('condition', models.CharField(default='NEW', max_length=255)),
                ('date_purchased', models.DateField()),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('transfer_to', models.CharField(max_length=100)),
                ('transfer_from', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('currency', models.CharField(default='USD', max_length=80)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=90)),
                ('date', models.DateField()),
                ('remarks', models.TextField(max_length=500)),
                ('status', models.CharField(default='IN PROGRESS', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEquipmentDetail',
            fields=[
                ('oed_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('room', models.CharField(default='Workshop', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_details', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='MotorVehicleDetail',
            fields=[
                ('mvd_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('engine_number', models.CharField(max_length=80, unique=True)),
                ('chassis_number', models.CharField(max_length=80, unique=True)),
                ('duty', models.DecimalField(decimal_places=2, default=0, max_digits=80)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('reg_number', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureAndFittingDetail',
            fields=[
                ('ffd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=100)),
                ('room', models.CharField(default='KITCHEN', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_details', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenterDetail',
            fields=[
                ('dcd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('warranty_end', models.DateField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datacenter_details', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEquipmentDetail',
            fields=[
                ('ced_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('warranty_end', models.DateField(blank=True)),
                ('room', models.CharField(default='SOFTWARE', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer_details', to='core.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
    ]
