# Generated by Django 4.1.3 on 2023-06-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetclassproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='land',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
        migrations.AddField(
            model_name='motorvehicle',
            name='asset_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.assetclassproperties'),
        ),
    ]
