# Generated by Django 4.1.3 on 2023-02-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_asset_grv_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenterdetail',
            options={'verbose_name': 'Datacenter Equipment'},
        ),
    ]
