# Generated by Django 4.1.3 on 2023-06-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_building_asset_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRevaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=85)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=85)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=85)),
                ('remarks', models.TextField(max_length=500)),
                ('asset_purchase_date', models.DateField()),
                ('perfomed_by', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
