# Generated by Django 4.1.3 on 2023-02-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_datacenterdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerequipmentdetail',
            options={'verbose_name': 'Computer Equipment'},
        ),
        migrations.AlterModelOptions(
            name='fixtureandfittingdetail',
            options={'verbose_name': 'Fixture and Fitting'},
        ),
        migrations.AlterModelOptions(
            name='motorvehicledetail',
            options={'verbose_name': 'Motor Vehicle'},
        ),
        migrations.AlterModelOptions(
            name='officeequipmentdetail',
            options={'verbose_name': 'Office Equipment'},
        ),
    ]
