# Generated by Django 4.1.3 on 2023-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assetrevaluationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdisposal',
            name='reason',
            field=models.TextField(max_length=255),
        ),
    ]
