# Generated by Django 4.1.3 on 2023-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assettransfer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='transfer_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
