# Generated by Django 4.1.3 on 2023-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_assettransfer_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='approved_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
