# Generated by Django 4.1.3 on 2023-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assettransfer_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransfer',
            name='approved_date',
            field=models.DateField(blank=True),
        ),
    ]
