# Generated by Django 4.1.3 on 2023-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_assettransfer_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransfer',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
