# Generated by Django 4.1.3 on 2023-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_assettransfer_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='approved_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
