# Generated by Django 4.1.3 on 2023-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assettransfer_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
